module.exports = {
  light: {
    '--background': '#f9fafb',
    '--foreground': '#111827',
    '--card': '#ffffff',
    '--card-foreground': '#111827',
    '--popover': '#ffffff',
    '--popover-foreground': '#111827',
    '--primary': '#2563eb',
    '--primary-foreground': '#ffffff',
    '--secondary': '#f3f4f6',
    '--secondary-foreground': '#111827',
    '--muted': '#f3f4f6',
    '--muted-foreground': '#4b5563',
    '--accent': '#f3f4f6',
    '--accent-foreground': '#111827',
    '--destructive': '#ef4444',
    '--destructive-foreground': '#ffffff',
    '--border': '#e5e7eb',
    '--input': '#e5e7eb',
    '--ring': '#2563eb',
  },
  dark: {
    '--background': '#111827',
    '--foreground': '#ffffff',
    '--card': '#1f2937',
    '--card-foreground': '#ffffff',
    '--popover': '#1f2937',
    '--popover-foreground': '#ffffff',
    '--primary': '#2563eb',
    '--primary-foreground': '#ffffff',
    '--secondary': '#1f2937',
    '--secondary-foreground': '#d1d5db',
    '--muted': '#1f2937',
    '--muted-foreground': '#9ca3af',
    '--accent': '#1f2937',
    '--accent-foreground': '#ffffff',
    '--destructive': '#ef4444',
    '--destructive-foreground': '#ffffff',
    '--border': '#374151',
    '--input': '#374151',
    '--ring': '#2563eb',
  },
};